version: 2.1

jobs:
  docker-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -f dockerfiles/Dockerfile -t $DOCKERHUB_USERNAME/techabraao:v1.0.0 .
      - run:
          name: DockerHub Login
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push to DockerHub
          command: docker push $DOCKERHUB_USERNAME/techabraao:v1.0.0

workflows:
  pipeline:
    jobs:
      - docker-push